version: '3.7'

volumes:
 dnsp_vol01:
 dnsp-db_vol01:
 #ssl-certificates_vol01:

services:
 dnsp-db:
    image: docker.adipsys.com:5000/dnsp-ha-db
    restart: always
    command: seed    
#   command: node dnsp-dbX
    environment:
      - XTRABACKUP_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ROOT_HOST=%
    deploy:
      placement:
             #max_replicas_per_node: 1
             constraints:
                 - node.role == manager
    volumes:
          - 'dnsp-db_vol01:/var/lib/mysql/'
         
# dnsp-dbX:
#    image: docker.adipsys.com:5000/dnsp-ha-db
#    restart: always
#    command: node dnsp-db
#    environment:
#      - XTRABACKUP_PASSWORD=${MYSQL_ROOT_PASSWORD}
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#      - MYSQL_ROOT_HOST=%
#    deploy:
#      placement:
#             #max_replicas_per_node: 1
#             constraints:
#                 - node.role != manager
#    volumes:
#          - 'dnsp-db_vol01:/var/lib/mysql/'

 dnsp-web:
    image: docker.adipsys.com:5000/dnsp-ha-web
    restart: always
    environment:
         - OPERATOR=${OPERATOR}
         - SERVER_NAME=${SERVER_NAME}
         - SERVER_ALIAS=${SERVER_ALIAS}
         - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
         - ADMIN_PASSWD=${ADMIN_PASSWD}
    deploy:
      placement:
    #          max_replicas_per_node: 1
               constraints:
                   - node.role == manager
    ports:
              - ${WEB_IHM_PORT}:80
              - ${WEB_IHM_SSL_PORT}:443
    volumes:
              #- 'ssl-certificates_vol01:/root/ssl_certificates/'
              - '/root/ssl_certificates/:/root/ssl_certificates/'
              - 'dnsp_vol01:/etc/powerdns/'
              - 'dnsp_vol01:/lock/'
    depends_on:
         - "dnsp-db"

 dnsp-pdns:
      image: docker.adipsys.com:5000/dnsp-ha-pdns
      restart: always
      environment:
               - RSYSLOG_SERVER=${RSYSLOG_SERVER}
      deploy:
        placement:
      #          max_replicas_per_node: 1
                 constraints:
                     - node.role == manager
      ports:
              - target: ${DNS_PORT}
                published: 53
                protocol: udp
                mode: host
      volumes:
              - 'dnsp_vol01:/etc/powerdns/'
              - 'dnsp_vol01:/logs/'
              - 'dnsp_vol01:/lock/'
      depends_on:
        - "dnsp-db"

 dnsp-es:
      restart: always
      environment:
         - discovery.type=single-node
      #deploy:
        #placement:
        #     max_replicas_per_node: 1
        #     constraints:
        #         - node.role != manager
      image: docker.adipsys.com:5000/dnsp-ha-es

 dnsp-ls:
      image: docker.adipsys.com:5000/dnsp-ha-ls
      restart: always
      environment:
         - discovery.type=single-node
    #  deploy:
    #      placement:
    #          max_replicas_per_node: 1
    #             constraints:
    #                 - node.role != manager
      depends_on:
              - "dnsp-es"

 dnsp-fb:
      image: docker.adipsys.com:5000/dnsp-ha-fb
      restart: always
      deploy:
          placement:
    #          max_replicas_per_node: 1
                 constraints:
                     - node.role == manager
      volumes:
              - 'dnsp_vol01:/logs/'
      depends_on:
              - "dnsp-es"
              - "dnsp-ls"
