version: '2.4'

volumes:
 pdns_vol01:
 pdns-db_vol01:

services:
 dnsp-db:
    image: docker.adipsys.com:5000/dnsp-ha-db
    restart: always
    environment:
      - DB_SERVICE_NAME=dbcluster
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=dnsprotect
      - MYSQL_USER=dnsprotect
      - MYSQL_PASSWORD=dnsprotect
    volumes:
          - 'pdns-db_vol01:/var/lib/mysql/'
          - 'pdns_vol01:/lock/'

 dnsp-web:
      image: docker.adipsys.com:5000/dnsp-ha-web
      restart: always
      environment:
         - SERVER_ALIAS=${SERVER_ALIAS}
         - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      ports:
              - 80:80
      volumes:
              - 'pdns_vol01:/etc/powerdns/'
              - 'pdns_vol01:/lock/'
      depends_on:
        - "dnsp-db"
      links:
        - "dnsp-db"
        - "dnsp-es"

 dnsp-pdns:
      image: docker.adipsys.com:5000/dnsp-ha-pdns
      restart: always
      ports:
              - 53:53/udp
      volumes:
              - 'pdns_vol01:/etc/powerdns/'
              - 'pdns_vol01:/logs/'
      depends_on:
        - "dnsp-db"
      links:
        - "dnsp-db"

 dnsp-es:
      restart: always
      environment:
         - discovery.type=single-node
      image: docker.adipsys.com:5000/dnsp-ha-es

 dnsp-ls:
      image: docker.adipsys.com:5000/dnsp-ha-ls
      restart: always
      environment:
         - discovery.type=single-node
      depends_on:
              - "dnsp-es"
      links:
              - "dnsp-es"

 dnsp-fb:
      image: docker.adipsys.com:5000/dnsp-ha-fb
      restart: always
      volumes:
              - 'pdns_vol01:/logs/'
      depends_on:
              - "dnsp-es"
              - "dnsp-ls"
      links:
              - "dnsp-ls"
